/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

int main(void)
{
    RCC->AHB1ENR |= (1U << 0);
    GPIOA->MODER |= (1U << 10);
    GPIOA->MODER &= ~(1U << 11);

    /* Loop forever */
	for(;;) {
        GPIOA->ODR ^= (1U << 5);
        for (volatile uint32_t i = 0; i < 0xEFFFF; i++);
    }
}
