/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "led.h"
#include "timer.h"
#include "uart.h"

int main(void)
{
	char str[] = "Flashed once again";
	size_t n = strlen(str);

	ledInit();
	tim2_1Hz_Init();
	uartInit();

    /* Loop forever */
	for(;;) {
		ledToggle();
		printf("len = %u\r\n", n);
		printf("%s\r\n", str);
		while (!(TIM2->SR & SR_UIF));
		TIM2->SR &= ~SR_UIF;
	}
}
